# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:
{
  environment.systemPackages = with pkgs; [
    msr-tools
  ];
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "ahci" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" "msr" ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = [ "iomem=relaxed" "msr.allow_writes=on" "split_lock_detect=off" "lockdown=none" ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/07c869c1-4962-4bb2-8507-cf6a38701e75";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/2F71-EBBA";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/9bc1ac5a-f9ad-4403-bbb0-44dc10465a5b"; }];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
